import { makeStyles } from "@material-ui/core/styles";
import Background from '../../../images/bannerbg.png';

export default makeStyles(() => ({
    root: {
        backgroundColor: '#2b5681',
        fontFamily:'Open Sans',
    },
    imgContainer: {
        // backgroundImage: `url(${Background})`,
        backgroundPosition: 'center',
        backgroundSize: 'contain',
        backgroundRepeat: 'yes',
        height: '200px',
        // marginBlockEnd: '20px',
        // borderBottomLeftRadius: '50%',
        // borderBottomRightRadius: '60%',
        marginBlockStart:'-100px',
        backgroundColor:'transparent',
        width:'100%'
    },
    imgContainerMobi: {
        backgroundPosition: 'center',
        backgroundSize: 'contain',
        backgroundRepeat: 'yes',
        height: 'auto',
        // marginBlockEnd: '20px',
        // borderBottomLeftRadius: '50%',
        // borderBottomRightRadius: '60%',
        marginBlockStart:'-60px',
        backgroundColor:'#2b5681',
        width:'100%'
    },
    image: {
        width: '100%',
        height: '200px',
        display: 'block',
        // // borderRadius: '10px',
        backgroundSize:'contain'
    },
    ribbon: {
        textOverflow: 'ellipsis',
        position: 'relative',
        top: '0%',
        float:'right',
        alignItems:'right',
        padding: '10px',
        backgroundColor: 'red',
        color: 'white',
        opacity: '0.8',
        maxWidth: 'auto',
        height: '7%',
        fontSize: '18px',
        fontWeight: '600',
        transition: '300ms',
        cursor: 'pointer',
        '&::before': {
        },
    },
    ribbon2: {
        textOverflow: 'ellipsis',
        position: 'relative',
        bottom: '-55%',
        float:'right',
        alignItems:'right',
        padding: '10px',
        backgroundColor: 'red',
        margin:0,
        color: 'white',
        opacity: '0.8',
        maxWidth: 'auto',
        height: '7%',
        fontSize: '18px',
        fontWeight: '600',
        '&::before': {
            content: ' ',
            position: 'absolute',
            width: '30px',
            height: 0,
            left: '-30px',
            top: '12px',
            borderWidth: '20px 10px',
            borderStyle: 'solid',
            borderColor: '#999 #999 #999 transparent',
        },
    },
    ribbon3: {
        textOverflow: 'ellipsis',
        position: 'relative',
        bottom: '-25%',
        float:'right',
        backgroundColor: 'whitesmoke',
        color: 'black',
        opacity: '0.8',
        maxWidth: 'auto',
        height: '7%',
        fontSize: '12px',
        transition: '300ms',
    },
}));